#!/usr/bin/env python3
"""Adversarial court for the delta-only inverse-dynamics hypothesis.

The filesystem motor ecology made displacement-only inference look unusually
strong. That can be real and still be ecology-specific. This court constructs
paired transitions from two different rotations such that the *same observed
displacement* is generated by different operators at different absolute states.
A delta-only selector is then information-theoretically ambiguous on each pair,
while an endpoint-aware selector can in principle disambiguate from state.

The goal is not to make delta-only lose everywhere. The goal is to discover the
boundary where it stops being a sufficient statistic and turn that boundary
into an adaptive architecture rather than a slogan.
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import math
import statistics
import sys
from pathlib import Path
from typing import Any

import torch

HERE = Path(__file__).resolve().parent
ABLATION_PATH = HERE / "operator_delta_ablation.py"


def load_ablation():
    spec = importlib.util.spec_from_file_location("archie_operator_delta_collision_ablation", ABLATION_PATH)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {ABLATION_PATH}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


A = load_ablation()
CORE = A.CORE


def rotation(theta: float) -> torch.Tensor:
    c, s = math.cos(theta), math.sin(theta)
    return torch.tensor([[c, -s], [s, c]], dtype=torch.float32)


def make_collision_dataset(pairs: int, seed: int, theta: float = math.pi / 3) -> tuple[torch.Tensor, torch.Tensor, list[str]]:
    if pairs < 20:
        raise ValueError("pairs>=20 required")
    gen = torch.Generator().manual_seed(seed)
    q_plus = rotation(theta)
    q_minus = rotation(-theta)
    eye = torch.eye(2)
    # Both (Q-I) matrices are invertible for nonzero non-2pi rotation.
    inv_plus = torch.linalg.inv(q_plus - eye)
    inv_minus = torch.linalg.inv(q_minus - eye)

    before: list[torch.Tensor] = []
    after: list[torch.Tensor] = []
    labels: list[str] = []
    for _ in range(pairs):
        # Shared displacement is the collision variable. Keep it away from zero
        # so the paired starting states remain well-conditioned.
        d = torch.randn(2, generator=gen)
        d = d + torch.sign(d + 1e-6) * 0.25
        x_plus = inv_plus @ d
        x_minus = inv_minus @ d
        before.extend([x_plus, x_minus])
        after.extend([q_plus @ x_plus, q_minus @ x_minus])
        labels.extend(["rot_plus", "rot_minus"])

    b = torch.stack(before)
    a = torch.stack(after)
    # Pair adjacency is preserved. Chronological split therefore contains both
    # classes on both sides for ordinary pair counts divisible by five.
    return b, a, labels


def collision_diagnostics(before: torch.Tensor, after: torch.Tensor, labels: list[str]) -> dict[str, Any]:
    delta = after - before
    pair_errors: list[float] = []
    ambiguous = 0
    for i in range(0, len(labels), 2):
        err = float((delta[i] - delta[i + 1]).abs().max().item())
        pair_errors.append(err)
        if labels[i] != labels[i + 1] and err < 1e-5:
            ambiguous += 1
    return {
        "pairs": len(pair_errors),
        "ambiguous_delta_pairs": ambiguous,
        "ambiguous_pair_rate": ambiguous / max(1, len(pair_errors)),
        "max_paired_delta_abs_error": max(pair_errors, default=0.0),
    }


def run_seed(seed: int, pairs: int, epochs: int, codes: int, lr: float, device: str) -> dict[str, Any]:
    before, after, labels = make_collision_dataset(pairs, seed)
    diag = collision_diagnostics(before, after, labels)
    before, after, normalization = CORE.robust_normalize(before, after)
    dev = torch.device(device)
    endpoint = A.train_variant(
        before,
        after,
        labels,
        selector="endpoint+delta",
        codes=codes,
        epochs=epochs,
        lr=lr,
        seed=seed,
        device=dev,
    )
    delta = A.train_variant(
        before,
        after,
        labels,
        selector="delta-only",
        codes=codes,
        epochs=epochs,
        lr=lr,
        seed=seed,
        device=dev,
    )
    eps = 1e-12
    return {
        "seed": seed,
        "collision": diag,
        "normalization": normalization,
        "endpoint_delta": endpoint,
        "delta_only": delta,
        "endpoint_over_delta_forward_mse": endpoint["test_forward_mse"] / max(eps, delta["test_forward_mse"]),
        "endpoint_over_delta_inverse_mse": endpoint["test_inverse_mse"] / max(eps, delta["test_inverse_mse"]),
        "effect_nmi_advantage_endpoint_minus_delta": endpoint["latent_vs_hand_effect_nmi"] - delta["latent_vs_hand_effect_nmi"],
        "valid": bool(endpoint["valid"] and delta["valid"] and diag["ambiguous_pair_rate"] == 1.0),
    }


def run_court(seeds: list[int], pairs: int, epochs: int, codes: int, lr: float, device: str) -> dict[str, Any]:
    runs = [run_seed(seed, pairs, epochs, codes, lr, device) for seed in seeds]
    fwd = [float(r["endpoint_over_delta_forward_mse"]) for r in runs]
    inv = [float(r["endpoint_over_delta_inverse_mse"]) for r in runs]
    nmi = [float(r["effect_nmi_advantage_endpoint_minus_delta"]) for r in runs]
    endpoint_wins = sum(x < 1.0 for x in fwd)
    strong_wins = sum(x <= 0.8 for x in fwd)
    passed = bool(
        all(r["valid"] for r in runs)
        and endpoint_wins >= len(runs) - 1
        and strong_wins >= (len(runs) + 1) // 2
        and statistics.median(fwd) < 0.8
        and statistics.median(nmi) > 0.0
    )
    return {
        "schema": "archie-action-latent/operator-delta-collision-court-v1",
        "pass": passed,
        "seeds": seeds,
        "pairs_per_seed": pairs,
        "runs": runs,
        "endpoint_forward_wins": endpoint_wins,
        "endpoint_strong_forward_wins": strong_wins,
        "median_endpoint_over_delta_forward_mse": statistics.median(fwd),
        "median_endpoint_over_delta_inverse_mse": statistics.median(inv),
        "median_endpoint_effect_nmi_advantage": statistics.median(nmi),
        "architectural_consequence": (
            "Use displacement as the minimal inverse-dynamics statistic only when its consequence classes are not state-ambiguous. "
            "When collision/conditional-entropy rises, route absolute state into the selector. Representation complexity should be learned/gated by ambiguity."
        ),
        "claim_boundary": (
            "PASS falsifies universal delta-only sufficiency on a deliberately state-dependent rotational ecology. It does not erase the 5-seed "
            "filesystem result where delta-only won; together the courts motivate an adaptive sufficient-statistic selector."
        ),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--seeds", default="7601,7602,7603,7604,7605")
    parser.add_argument("--pairs", type=int, default=240)
    parser.add_argument("--epochs", type=int, default=120)
    parser.add_argument("--codes", type=int, default=4)
    parser.add_argument("--lr", type=float, default=3e-3)
    parser.add_argument("--device", default="cpu")
    parser.add_argument("--output")
    args = parser.parse_args()
    seeds = [int(x.strip()) for x in args.seeds.split(",") if x.strip()]
    result = run_court(seeds, args.pairs, args.epochs, args.codes, args.lr, args.device)
    text = json.dumps(result, indent=2, sort_keys=True)
    if args.output:
        path = Path(args.output).expanduser().resolve()
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text + "\n", "utf-8")
    print(text)
    raise SystemExit(0 if result["pass"] else 1)


if __name__ == "__main__":
    main()
