export const COPY = Object.freeze({
  brand: 'SIDEWAYS',
  kicker: 'YOUR STUFF. ONE FEED.',
  headline: 'PICK AN APP. BRING YOUR STUFF.',
  intro: 'Start with Instagram, Reddit, TikTok, YouTube, Spotify, X, bookmarks, or any files.',
  privacy: 'Your files stay on this device.',
  emptyTitle: 'PICK AN APP.',
  emptyBody: 'Choose one. Bring over your stuff. That’s it.',
  emptyAction: 'PICK AN APP',
  openPackAction: 'OPEN A SIDEWAYS BACKUP',
  sourceLabel: 'FROM YOUR STUFF',
  localBadge: 'STAYS ON THIS DEVICE',
  addHint: 'INSTAGRAM, REDDIT, TIKTOK, YOUTUBE, SPOTIFY, X, BOOKMARKS, OR FILES',
  ready: 'START HERE',
  storage: 'SAVED ON THIS DEVICE',
  storageUnknown: 'CHECKING YOUR SAVED FEED…',
  storagePersistent: 'YOUR FEED WILL STAY HERE',
  storageTemporary: 'THIS BROWSER MAY CLEAR YOUR FEED LATER',
  storageAction: 'KEEP MY FEED',
  saved: 'SAVED',
  profile: 'PROFILE',
  footer: 'YOUR STUFF, RECOMPOSED',
  feedLearning: 'GOOD START.',
  feedLearningBody: 'Add another app or just use the feed. Every keep, read, and skip changes what comes next.',
  feedAwake: 'YOUR FEED IS READY.',
  feedAwakeBody: 'Use it normally. Keep what you like, skip what you do not, and add another app whenever you want.',
  importTitle: 'PICK AN APP.',
  importBody: 'Tap one below. Get the download. Then choose the files.',
  profileTitle: 'NAME YOUR FEED (OPTIONAL)',
  profileBody: 'Skip this unless you want a name shown inside Sideways.',
  profileName: 'NAME',
  profileHandle: 'HANDLE (OPTIONAL)',
  profileSave: 'SAVE',
  profileSkip: 'SKIP',
  setupSaved: 'SAVED',
  chooseSource: 'PICK AN APP',
  chooseSourceBody: 'Instagram, Reddit, TikTok—whatever you use.',
  queueEmpty: 'Pick an app, then choose the files you downloaded.',
  importReady: 'READY',
  importRun: 'ADD TO MY FEED',
  importDone: 'DONE. YOUR FEED HAS NEW STUFF.',
  importOpen: 'OPEN MY FEED',
  formats: ['SOCIAL APPS', 'BOOKMARKS', 'DOCUMENTS', 'PHOTOS + VIDEO', 'SPREADSHEETS + DATA FILES', 'TEXT + LINKS']
});

export function copy(key, fallback = '') {
  return COPY[key] ?? fallback;
}
