export const COPY = Object.freeze({
  brand: 'SIDEWAYS',
  kicker: 'A FEED BUILT FROM YOUR ACTUAL HISTORY',
  headline: 'BRING OVER THE INTERNET YOU ALREADY LIKED.',
  intro: 'Choose an app, download your history, and drop it here. Sideways turns your own saves, posts, likes, links, and watch history into a feed you can shape.',
  privacy: 'Your files stay in this browser. Nothing is uploaded.',
  emptyTitle: 'LET’S BUILD YOUR FEED.',
  emptyBody: 'Start with one app or a folder of files. You can add more whenever you want.',
  emptyAction: 'CHOOSE AN APP',
  openPackAction: 'OPEN A SIDEWAYS BACKUP',
  sourceLabel: 'FROM YOUR HISTORY',
  localBadge: 'PRIVATE ON THIS DEVICE',
  addHint: 'REDDIT, INSTAGRAM, TIKTOK, YOUTUBE, SPOTIFY, X, BOOKMARKS, OR FILES',
  ready: 'NEW HERE',
  storage: 'SAVED ON THIS DEVICE',
  storageUnknown: 'CHECKING LOCAL STORAGE…',
  storagePersistent: 'YOUR LIBRARY IS PROTECTED',
  storageTemporary: 'KEEP THIS LIBRARY ON THIS DEVICE',
  storageAction: 'PROTECT MY LIBRARY',
  saved: 'SAVED',
  profile: 'PROFILE',
  footer: 'YOUR HISTORY, RECOMPOSED',
  feedLearning: 'GOOD START.',
  feedLearningBody: 'Add another app or keep using the feed. Every keep, read, and skip changes what rises next.',
  feedAwake: 'YOUR FEED IS READY.',
  feedAwakeBody: 'Use it normally. Keep what matters, skip what does not, and add another source when the feed gets narrow.',
  importTitle: 'CHOOSE WHERE TO START.',
  importBody: 'Pick an app below. We’ll show you exactly where to get your data and which files to choose.',
  profileTitle: 'WHAT SHOULD WE CALL YOU?',
  profileBody: 'This stays local too. It only labels your profile and your imported posts.',
  profileName: 'NAME',
  profileHandle: 'HANDLE (OPTIONAL)',
  profileSave: 'SAVE AND CHOOSE AN APP',
  profileSkip: 'SKIP FOR NOW',
  setupSaved: 'PROFILE SAVED',
  chooseSource: 'CHOOSE AN APP',
  chooseSourceBody: 'Start with the place that knows your taste best. You can combine as many as you want.',
  queueEmpty: 'Choose files from an app above. We will inspect them before anything is added.',
  importReady: 'READY TO ADD',
  importRun: 'ADD TO MY FEED',
  importDone: 'YOUR FEED HAS NEW MATERIAL',
  importOpen: 'OPEN MY FEED',
  formats: ['SOCIAL EXPORTS', 'BOOKMARKS + RSS', 'PDF + OFFICE', 'PHOTOS + VIDEO', 'JSON + CSV', 'TEXT + LINKS']
});

export function copy(key, fallback = '') {
  return COPY[key] ?? fallback;
}
